// ============================================================================
// Seed script: Import pickup/meeting strangers scene phrases
// Run: npx tsx prisma/seed-pickup.ts
// ============================================================================

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface Phrase {
  scene: string;
  zh: string;
  vi: string;
  pinyin: string;
  culture: string;
  sortOrder: number;
}

const phrases: Phrase[] = [];
let order = 0;

function add(zh: string, vi: string, pinyin: string, culture: string) {
  phrases.push({ scene: "pickup", zh, vi, pinyin, culture, sortOrder: order++ });
}

// ── table.csv — 搭讪开场白 (50) ──
add("嗨，你一个人吗？可以聊聊吗？", "Chào em, em đi một mình hả? Nói chuyện chút được không ạ?", "Chào em, em đi một mình hả?...", "最自然的搭讪开场白");
add("你看起来很眼熟，我们以前见过吗？", "Em trông quen quen, mình gặp nhau ở đâu rồi nhỉ?", "Em trông quen quen...", "经典搭讪套路");
add("这里风景真好，你经常来吗？", "Cảnh ở đây đẹp quá, em hay đến đây hả?", "Cảnh ở đây đẹp quá...", "借环境起话题");
add("你笑起来真可爱", "Em cười dễ thương quá ạ", "Em cười dễ thương quá ạ", "直接夸奖，效果好");
add("我有点喜欢你了", "Anh hơi thích em rồi ạ", "Anh hơi thích em rồi ạ", "大胆直白表白");
add("可以加你Zalo吗？", "Mình add Zalo nhé?", "Mình add Zalo nhé?", "越南社交必备，Zalo = 微信");
add("你今天真漂亮", "Hôm nay em xinh quá ạ", "Hôm nay em xinh quá ạ", "夸女生漂亮必备句");
add("你的眼睛好亮", "Mắt em sáng quá ạ", "Mắt em sáng quá ạ", "夸眼睛");
add("你是本地人吗？", "Em là người Đà Nẵng hả?", "Em là người Đà Nẵng hả?", "询问是否本地人，岘港版");
add("第一次见面就觉得你很特别", "Lần đầu gặp em anh đã thấy em đặc biệt lắm ạ", "Lần đầu gặp em...", "一见钟情表达");
add("你在听什么歌？分享给我听", "Em đang nghe nhạc gì hay thế? Share với anh ạ", "Em đang nghe nhạc gì hay thế?...", "借音乐起话题");
add("可以坐旁边吗？", "Anh ngồi cạnh em được không ạ?", "Anh ngồi cạnh em được không ạ?", "礼貌请求");
add("你来岘港旅游吗？", "Em đến Đà Nẵng du lịch hả?", "Em đến Đà Nẵng du lịch hả?", "常用搭讪问题");
add("你的笑容让我心动", "Nụ cười của em làm anh rung động ạ", "Nụ cười của em làm anh rung động ạ", "浪漫表达");
add("这里人好多，你不怕吗？", "Ở đây đông người, em không sợ hả?", "Ở đây đông người...", "关心式搭讪");
add("你喜欢海滩还是咖啡厅？", "Em thích biển hay quán cà phê hơn ạ?", "Em thích biển hay quán cà phê hơn ạ?", "选择题搭讪");
add("我是游客，你可以当导游吗？", "Anh là du khách, em làm hướng dẫn viên cho anh nhé?", "Anh là du khách...", "幽默邀请");
add("你拍照好专业啊", "Em chụp ảnh chuyên nghiệp quá ạ", "Em chụp ảnh chuyên nghiệp quá ạ", "夸拍照技术");
add("借个火/充电宝可以吗？", "Cho anh mượn lửa / sạc dự phòng được không ạ?", "Cho anh mượn lửa...", "经典借东西搭讪");
add("你的包好可爱", "Cái túi của em dễ thương quá ạ", "Cái túi của em dễ thương quá ạ", "夸配饰");
add("你戴的耳环真好看", "Bông tai em đeo đẹp quá ạ", "Bông tai em đeo đẹp quá ạ", "夸配饰细节");
add("今天天气好，你出来散步吗？", "Hôm nay trời đẹp, em ra ngoài dạo hả?", "Hôm nay trời đẹp...", "天气话题搭讪");
add("你一个人看海吗？", "Em đi ngắm biển một mình hả?", "Em đi ngắm biển một mình hả?", "海边搭讪");
add("你的发型很特别", "Kiểu tóc em đặc biệt quá ạ", "Kiểu tóc em đặc biệt quá ạ", "夸发型");
add("可以认识一下吗？", "Mình làm quen nhé?", "Mình làm quen nhé?", "最直接的搭讪方式");
add("你看起来很开心，什么事啊？", "Em trông vui quá, có chuyện gì vui hả?", "Em trông vui quá...", "观察式搭讪");
add("这里风好大，你冷不冷？", "Gió lớn quá, em có lạnh không ạ?", "Gió lớn quá...", "关心式搭讪");
add("你喜欢日落还是日出？", "Em thích hoàng hôn hay bình minh hơn ạ?", "Em thích hoàng hôn hay bình minh hơn ạ?", "浪漫话题");
add("我可以给你拍照吗？", "Anh chụp cho em vài tấm được không ạ?", "Anh chụp cho em vài tấm được không ạ?", "帮拍照搭讪");
add("你戴的项链好漂亮", "Dây chuyền em đeo đẹp quá ạ", "Dây chuyền em đeo đẹp quá ạ", "夸配饰");
add("第一次来岘港吗？", "Lần đầu em đến Đà Nẵng hả?", "Lần đầu em đến Đà Nẵng hả?", "旅行话题");
add("你一个人旅行吗？", "Em đi du lịch một mình hả?", "Em đi du lịch một mình hả?", "了解同行情况");
add("你喜欢吃海鲜吗？", "Em thích ăn hải sản không ạ?", "Em thích ăn hải sản không ạ?", "美食话题搭讪");
add("你的鞋子好潮", "Đôi giày em mang chất quá ạ", "Đôi giày em mang chất quá ạ", "夸穿搭");
add("可以合影一张吗？", "Mình chụp chung một tấm được không ạ?", "Mình chụp chung một tấm được không ạ?", "合影搭讪");
add("你在等朋友吗？", "Em đang đợi bạn hả?", "Em đang đợi bạn hả?", "关心式开场");
add("你的口音好听", "Giọng em nghe hay quá ạ", "Giọng em nghe hay quá ạ", "夸声音");
add("这里拍照好看，你试试这个角度", "Ở đây chụp đẹp lắm, em thử góc này xem ạ", "Ở đây chụp đẹp lắm...", "拍照搭讪");
add("你戴的帽子真可爱", "Cái mũ em đội dễ thương quá ạ", "Cái mũ em đội dễ thương quá ạ", "夸配饰");
add("今天好热，你不热吗？", "Hôm nay nóng quá, em không nóng hả?", "Hôm nay nóng quá...", "天气话题搭讪");
add("可以帮我拍张照吗？", "Em chụp giúp anh một tấm được không ạ?", "Em chụp giúp anh một tấm được không ạ?", "请帮忙式搭讪");
add("你喜欢听什么音乐？", "Em thích nghe nhạc gì ạ?", "Em thích nghe nhạc gì ạ?", "兴趣话题");
add("你一个人坐这里干嘛？", "Em ngồi một mình ở đây làm gì ạ?", "Em ngồi một mình ở đây làm gì ạ?", "关心式搭讪");
add("你的指甲好漂亮", "Móng tay em sơn đẹp quá ạ", "Móng tay em sơn đẹp quá ạ", "夸细节");
add("可以问你名字吗？", "Anh hỏi tên em được không ạ?", "Anh hỏi tên em được không ạ?", "最基础的交友问题");
add("你看起来很温柔", "Em trông dịu dàng quá ạ", "Em trông dịu dàng quá ạ", "夸气质");
add("这里浪好大，你不怕吗？", "Sóng to quá, em không sợ hả?", "Sóng to quá...", "海边关心搭讪");
add("你戴的眼镜好潮", "Cặp kính em đeo chất quá ạ", "Cặp kính em đeo chất quá ạ", "夸配饰");
add("可以交换Instagram吗？", "Mình trao đổi Instagram nhé?", "Mình trao đổi Instagram nhé?", "加社交媒体");
add("不好意思，我忍不住想认识你", "Xin lỗi, anh không kìm được muốn làm quen với em ạ", "Xin lỗi, anh không kìm được...", "真诚式搭讪");

// ── table(1).csv — 约咖啡 (50) ──
add("我们去喝杯咖啡好吗？", "Mình đi uống cà phê nhé?", "Mình đi uống cà phê nhé?", "最简单的约咖啡");
add("想请你喝咖啡，可以吗？", "Anh mời em uống cà phê được không ạ?", "Anh mời em uống cà phê được không ạ?", "礼貌邀请");
add("附近有家咖啡店不错，一起去？", "Gần đây có quán cà phê hay lắm, đi cùng anh nhé?", "Gần đây có quán cà phê hay lắm...", "推荐店邀请");
add("今天天气好，喝杯咖啡聊聊？", "Hôm nay trời đẹp, uống cà phê nói chuyện nhé?", "Hôm nay trời đẹp...", "天气+咖啡");
add("你喜欢喝什么咖啡？我请你", "Em thích cà phê gì? Anh mời em ạ", "Em thích cà phê gì?...", "大方请客");
add("去喝咖啡吧，我知道一家view海的", "Đi cà phê đi, anh biết quán view biển hay lắm ạ", "Đi cà phê đi...", "推荐海景咖啡");
add("陪我喝杯咖啡好不好？", "Em đi uống cà phê với anh nhé?", "Em đi uống cà phê với anh nhé?", "温柔邀请");
add("饿不饿？先喝咖啡再吃饭", "Em đói chưa? Uống cà phê trước rồi ăn nhé", "Em đói chưa?...", "关心+邀请");
add("下午有空吗？一起去咖啡厅", "Chiều nay em rảnh không? Cùng đi quán cà phê ạ", "Chiều nay em rảnh không?...", "确认时间再邀请");
add("我请你喝杯冰咖啡解暑", "Anh mời em ly cà phê sữa đá nhé", "Anh mời em ly cà phê sữa đá nhé", "越南经典冰咖啡");
add("想和你一起去喝咖啡，看日落", "Anh muốn cùng em đi uống cà phê ngắm hoàng hôn ạ", "Anh muốn cùng em đi uống cà phê...", "浪漫咖啡约会");
add("去那家网红咖啡店好吗？", "Đi quán cà phê hot trend kia nhé?", "Đi quán cà phê hot trend kia nhé?", "网红店邀请");
add("你现在忙吗？不然喝杯咖啡去", "Em đang bận không? Không thì đi uống cà phê ạ", "Em đang bận không?...", "随意邀请");
add("我知道一家咖啡店安静又浪漫", "Anh biết quán cà phê yên tĩnh mà lãng mạn lắm ạ", "Anh biết quán cà phê yên tĩnh...", "推荐浪漫咖啡");
add("喝咖啡聊聊人生好吗？", "Uống cà phê nói chuyện cuộc đời nhé?", "Uống cà phê nói chuyện cuộc đời nhé?", "深度话题邀请");
add("今天请你喝咖啡，庆祝遇见你", "Hôm nay anh mời em cà phê, kỷ niệm gặp em ạ", "Hôm nay anh mời em cà phê...", "浪漫理由");
add("去喝咖啡吧，我请客", "Đi uống cà phê đi, anh bao ạ", "Đi uống cà phê đi, anh bao ạ", "大方请客，bao=请客");
add("你喜欢甜的还是苦的咖啡？", "Em thích cà phê ngọt hay đắng ạ?", "Em thích cà phê ngọt hay đắng ạ?", "了解口味");
add("附近咖啡厅很多，我们随便挑一家", "Quán cà phê gần đây nhiều lắm, mình chọn đại nhé", "Quán cà phê gần đây nhiều lắm...", "随性邀请");
add("喝完咖啡我们去散步好吗？", "Uống cà phê xong mình đi dạo nhé?", "Uống cà phê xong mình đi dạo nhé?", "咖啡+散步");
add("我想请你喝杯拿铁", "Anh muốn mời em ly latte ạ", "Anh muốn mời em ly latte ạ", "具体饮品邀请");
add("去喝咖啡放松一下吧", "Đi uống cà phê thư giãn chút nhé", "Đi uống cà phê thư giãn chút nhé", "放松式邀请");
add("你喜欢哪家连锁咖啡？", "Em thích chuỗi cà phê nào ạ?", "Em thích chuỗi cà phê nào ạ?", "越南有很多连锁咖啡品牌");
add("喝咖啡的时候我可以听你讲故事吗？", "Khi uống cà phê anh nghe em kể chuyện được không ạ?", "Khi uống cà phê anh nghe em...", "浪漫式邀请");
add("今天我心情好，想请你喝咖啡", "Hôm nay anh vui, muốn mời em cà phê ạ", "Hôm nay anh vui...", "分享心情");
add("去喝咖啡庆祝周末吧", "Đi uống cà phê mừng cuối tuần nhé", "Đi uống cà phê mừng cuối tuần nhé", "周末邀请");
add("你现在在哪里？附近有咖啡店吗？", "Em đang ở đâu? Gần đó có quán cà phê không ạ?", "Em đang ở đâu?...", "主动出击");
add("喝杯咖啡再回家好吗？", "Uống ly cà phê rồi về nhé?", "Uống ly cà phê rồi về nhé?", "延长相处时间");
add("我知道一家咖啡店有 view 韩江", "Anh biết quán cà phê view sông Hàn đẹp lắm ạ", "Anh biết quán cà phê view sông Hàn...", "岘港韩江是著名景点");
add("去喝咖啡吧，别拒绝我", "Đi uống cà phê đi, đừng từ chối anh ạ", "Đi uống cà phê đi...", "撒娇式邀请");
add("想和你一起喝咖啡看书", "Anh muốn cùng em uống cà phê đọc sách ạ", "Anh muốn cùng em uống cà phê...", "文艺咖啡约");
add("你喜欢加糖还是黑咖啡？", "Em thích thêm đường hay đen ạ?", "Em thích thêm đường hay đen ạ?", "了解口味偏好");
add("喝咖啡的时候我可以问你一些问题吗？", "Khi uống cà phê anh hỏi em vài câu được không ạ?", "Khi uống cà phê anh hỏi em...", "好奇式邀请");
add("去喝咖啡庆祝我们认识吧", "Đi uống cà phê kỷ niệm chúng ta quen nhau nhé", "Đi uống cà phê kỷ niệm...", "纪念相识");
add("今天请你喝咖啡，下次你请我", "Hôm nay anh mời em cà phê, lần sau em mời anh ạ", "Hôm nay anh mời em cà phê...", "暗示下次还约");
add("你现在有空吗？去喝咖啡", "Em rảnh không? Đi uống cà phê ạ", "Em rảnh không?...", "直接邀请");
add("我想请你喝杯咖啡，感谢你今天陪我", "Anh muốn mời em cà phê, cảm ơn em hôm nay đi cùng anh ạ", "Anh muốn mời em cà phê...", "感恩式邀请");
add("喝咖啡聊聊梦想好吗？", "Uống cà phê nói chuyện ước mơ nhé?", "Uống cà phê nói chuyện ước mơ nhé?", "深度话题");
add("去那家有 live music 的咖啡店", "Đi quán cà phê có nhạc sống nhé", "Đi quán cà phê có nhạc sống nhé", "音乐咖啡店");
add("你喜欢喝 cà phê sữa đá 吗？", "Em thích cà phê sữa đá không ạ?", "Em thích cà phê sữa đá không ạ?", "越南最经典的咖啡");
add("喝完咖啡我们去海滩走走", "Uống cà phê xong mình đi dạo biển nhé", "Uống cà phê xong mình đi dạo biển nhé", "海滩散步");
add("想和你一起去喝咖啡看书", "Anh muốn cùng em đi uống cà phê đọc sách ạ", "Anh muốn cùng em đi uống cà phê...", "文艺咖啡约");
add("今天我请客，喝咖啡去", "Hôm nay anh bao, đi uống cà phê ạ", "Hôm nay anh bao...", "bao=请客");
add("你现在在哪里？我来接你去喝咖啡", "Em đang ở đâu? Anh qua đón em đi cà phê ạ", "Em đang ở đâu?...", "主动接人");
add("喝杯咖啡放松心情", "Uống cà phê thư giãn tâm trạng nhé", "Uống cà phê thư giãn tâm trạng nhé", "放松邀请");
add("去喝咖啡庆祝今天遇见你", "Đi uống cà phê mừng hôm nay gặp em nhé", "Đi uống cà phê mừng hôm nay gặp em nhé", "浪漫理由");
add("你喜欢喝 cà phê trứng 吗？", "Em thích cà phê trứng không ạ?", "Em thích cà phê trứng không ạ?", "越南特色蛋咖啡");
add("最后一次问：去喝咖啡吗？", "Lần cuối hỏi: đi uống cà phê không em?", "Lần cuối hỏi: đi uống cà phê không em?", "幽默的最后邀请");

// ── table(2).csv — 咖啡聊天话题 (50) ──
add("这杯咖啡好喝吗？", "Ly cà phê này ngon không ạ?", "Ly cà phê này ngon không ạ?", "咖啡聊天开场");
add("你平时喜欢来咖啡厅吗？", "Em hay đến quán cà phê không ạ?", "Em hay đến quán cà phê không ạ?", "了解日常习惯");
add("这里的音乐不错，你喜欢吗？", "Nhạc ở đây hay nhỉ, em thích không ạ?", "Nhạc ở đây hay nhỉ...", "环境话题");
add("你喜欢加奶还是黑咖啡？", "Em thích thêm sữa hay đen ạ?", "Em thích thêm sữa hay đen ạ?", "咖啡口味话题");
add("今天你点了什么咖啡？", "Hôm nay em gọi cà phê gì ạ?", "Hôm nay em gọi cà phê gì ạ?", "饮品话题");
add("这里的风景真不错，你觉得呢？", "View ở đây đẹp quá, em thấy sao ạ?", "View ở đây đẹp quá...", "环境评价");
add("你周末都喜欢做什么？", "Cuối tuần em hay làm gì ạ?", "Cuối tuần em hay làm gì ạ?", "周末话题");
add("你喜欢甜一点还是苦一点的咖啡？", "Em thích cà phê ngọt hay đắng ạ?", "Em thích cà phê ngọt hay đắng ạ?", "口味偏好");
add("这家的冰咖啡真不错", "Quán này cà phê sữa đá ngon lắm ạ", "Quán này cà phê sữa đá ngon lắm ạ", "推荐饮品");
add("你平时听什么类型的音乐？", "Em thích nghe thể loại nhạc gì ạ?", "Em thích nghe thể loại nhạc gì ạ?", "音乐爱好");
add("今天天气真好，适合喝咖啡", "Hôm nay trời đẹp, thích hợp uống cà phê ạ", "Hôm nay trời đẹp...", "天气话题");
add("你来岘港多久了？", "Em đến Đà Nẵng bao lâu rồi ạ?", "Em đến Đà Nẵng bao lâu rồi ạ?", "了解背景");
add("你最喜欢岘港的哪个地方？", "Em thích chỗ nào nhất ở Đà Nẵng ạ?", "Em thích chỗ nào nhất ở Đà Nẵng ạ?", "岘港景点话题");
add("你喜欢看电影吗？", "Em thích xem phim không ạ?", "Em thích xem phim không ạ?", "兴趣话题");
add("最近你都在忙什么？", "Dạo này em bận gì ạ?", "Dạo này em bận gì ạ?", "了解近况");
add("你一天喝几杯咖啡？", "Em uống cà phê mấy ly một ngày ạ?", "Em uống cà phê mấy ly một ngày ạ?", "咖啡习惯");
add("这家的蛋糕很好吃，你要试试吗？", "Bánh ở đây ngon lắm, em thử không ạ?", "Bánh ở đây ngon lắm...", "推荐甜点");
add("你喜欢拍照吗？", "Em thích chụp ảnh không ạ?", "Em thích chụp ảnh không ạ?", "爱好话题");
add("岘港有很多好看的咖啡厅", "Đà Nẵng có nhiều quán cà phê đẹp lắm ạ", "Đà Nẵng có nhiều quán cà phê đẹp lắm ạ", "分享岘港信息");
add("你更喜欢越南咖啡还是星巴克？", "Em thích cà phê Việt Nam hay Starbucks hơn ạ?", "Em thích cà phê Việt Nam hay Starbucks hơn ạ?", "品牌偏好");
add("你喜欢热咖啡还是冰咖啡？", "Em thích cà phê nóng hay lạnh ạ?", "Em thích cà phê nóng hay lạnh ạ?", "温度偏好");
add("今天你有什么计划？", "Hôm nay em có kế hoạch gì ạ?", "Hôm nay em có kế hoạch gì ạ?", "了解计划");
add("喝咖啡的时候你喜欢吃什么？", "Khi uống cà phê em thích ăn gì ạ?", "Khi uống cà phê em thích ăn gì ạ?", "搭配话题");
add("你的工作是做什么的？", "Công việc của em là gì ạ?", "Công việc của em là gì ạ?", "工作话题");
add("你喜欢旅行吗？", "Em có hay đi du lịch không ạ?", "Em có hay đi du lịch không ạ?", "旅行话题");
add("喝咖啡时你喜欢听什么音乐？", "Khi uống cà phê em thích nghe nhạc gì ạ?", "Khi uống cà phê em thích nghe nhạc gì ạ?", "音乐偏好");
add("你喜欢看书吗？", "Em thích đọc sách không ạ?", "Em thích đọc sách không ạ?", "阅读爱好");
add("你最喜欢的花是什么？", "Em thích hoa gì nhất ạ?", "Em thích hoa gì nhất ạ?", "花卉话题");
add("你最喜欢的颜色是什么？", "Em thích màu gì nhất ạ?", "Em thích màu gì nhất ạ?", "颜色偏好");
add("你喜欢养宠物吗？", "Em thích thú cưng không ạ?", "Em thích thú cưng không ạ?", "宠物话题");
add("你最喜欢岘港的哪个季节？", "Em thích mùa nào nhất ở Đà Nẵng ạ?", "Em thích mùa nào nhất ở Đà Nẵng ạ?", "季节话题");
add("你更喜欢吃早餐还是晚餐？", "Em thích ăn sáng hay ăn tối hơn ạ?", "Em thích ăn sáng hay ăn tối hơn ạ?", "饮食习惯");
add("你更喜欢去海边还是去山里？", "Em thích đi biển hay đi núi ạ?", "Em thích đi biển hay đi núi ạ?", "旅行偏好");
add("你喜欢听播客吗？", "Em thích nghe podcast không ạ?", "Em thích nghe podcast không ạ?", "媒体偏好");
add("你喜欢什么运动？", "Em thích chơi thể thao gì ạ?", "Em thích chơi thể thao gì ạ?", "运动话题");
add("你喜欢看哪种电影？", "Em thích phim gì ạ?", "Em thích phim gì ạ?", "电影偏好");
add("你喜欢吃辣吗？", "Em thích ăn cay không ạ?", "Em thích ăn cay không ạ?", "口味偏好");
add("你更喜欢喝茶还是咖啡？", "Em thích uống trà hay cà phê hơn ạ?", "Em thích uống trà hay cà phê hơn ạ?", "饮品偏好");
add("你喜欢一个人旅行还是和朋友一起？", "Em thích đi du lịch một mình hay đi cùng bạn ạ?", "Em thích đi du lịch một mình hay đi cùng bạn ạ?", "旅行方式");
add("你喜欢听越南歌还是外文歌？", "Em thích nghe nhạc Việt hay nhạc ngoại ạ?", "Em thích nghe nhạc Việt hay nhạc ngoại ạ?", "音乐偏好");
add("你喜欢拍风景照还是自拍？", "Em thích chụp ảnh phong cảnh hay chân dung ạ?", "Em thích chụp ảnh phong cảnh hay chân dung ạ?", "摄影偏好");
add("你喜欢读什么类型的书？", "Em thích đọc sách gì ạ?", "Em thích đọc sách gì ạ?", "阅读偏好");
add("你喜欢做饭吗？", "Em thích nấu ăn không ạ?", "Em thích nấu ăn không ạ?", "做饭话题");
add("你最喜欢的水果是什么？", "Em thích hoa quả gì nhất ạ?", "Em thích hoa quả gì nhất ạ?", "水果话题");
add("你更喜欢早起还是晚睡？", "Em thích dậy sớm hay ngủ muộn ạ?", "Em thích dậy sớm hay ngủ muộn ạ?", "生活习惯");
add("今天跟你喝咖啡真开心", "Hôm nay uống cà phê với em vui thật ạ", "Hôm nay uống cà phê với em vui thật ạ", "结束语表达开心");

// ── table(3).csv — 情感升温 (50) ──
add("跟你聊天真舒服", "Nói chuyện với em thoải mái quá ạ", "Nói chuyện với em thoải mái quá ạ", "表达舒适感");
add("我觉得我们很合拍", "Anh thấy mình hợp nhau lắm ạ", "Anh thấy mình hợp nhau lắm ạ", "表达默契");
add("你懂我说的感觉吗？", "Em có hiểu cảm giác anh nói không ạ?", "Em có hiểu cảm giác anh nói không ạ?", "寻求共鸣");
add("我好想每天都跟你聊天", "Anh muốn chat với em mỗi ngày ạ", "Anh muốn chat với em mỗi ngày ạ", "表达想念");
add("你分享的东西我都喜欢", "Những gì em chia sẻ anh đều thích ạ", "Những gì em chia sẻ anh đều thích ạ", "认可对方");
add("我们好像认识很久了", "Hình như mình quen nhau lâu rồi ấy nhỉ", "Hình như mình quen nhau lâu rồi ấy nhỉ", "表达亲切感");
add("你今天开心吗？我想让你更开心", "Hôm nay em vui không ạ? Anh muốn em vui hơn nữa", "Hôm nay em vui không ạ?...", "关心+表白");
add("我可以叫你小可爱吗？", "Anh gọi em là cưng được không ạ?", "Anh gọi em là cưng được không ạ?", "cưng=亲爱的/小可爱");
add("你的想法好特别，我学到了", "Ý kiến em hay quá, anh học được nhiều ạ", "Ý kiến em hay quá...", "赞赏对方观点");
add("跟你在一起时间过得飞快", "Ở bên em thời gian trôi nhanh quá ạ", "Ở bên em thời gian trôi nhanh quá ạ", "享受相处时光");
add("我喜欢听你说话", "Anh thích nghe em nói ạ", "Anh thích nghe em nói ạ", "表达关注");
add("你今天穿的衣服好配你", "Hôm nay em mặc đồ hợp quá ạ", "Hôm nay em mặc đồ hợp quá ạ", "夸穿搭");
add("我们有很多共同点", "Mình có nhiều điểm chung lắm ạ", "Mình có nhiều điểm chung lắm ạ", "强调共鸣");
add("你饿不饿？我点东西给你吃", "Em đói chưa? Anh gọi đồ ăn cho em nhé", "Em đói chưa?...", "关心式照顾");
add("我可以抱你一下吗？", "Anh ôm em một cái được không ạ?", "Anh ôm em một cái được không ạ?", "征求同意的亲密请求");
add("你今天好香", "Hôm nay em thơm quá ạ", "Hôm nay em thơm quá ạ", "夸香水");
add("跟你在一起我很安心", "Ở bên em anh thấy yên tâm lắm ạ", "Ở bên em anh thấy yên tâm lắm ạ", "表达安全感");
add("你是我的开心果", "Em là liều thuốc vui của anh ạ", "Em là liều thuốc vui của anh ạ", "比喻快乐源泉");
add("我好想知道你更多", "Anh muốn biết thêm về em ạ", "Anh muốn biết thêm về em ạ", "表达好奇和兴趣");
add("你今天心情怎么样？", "Hôm nay tâm trạng em thế nào ạ?", "Hôm nay tâm trạng em thế nào ạ?", "关心情绪");
add("你的声音好温柔", "Giọng em dịu dàng quá ạ", "Giọng em dịu dàng quá ạ", "夸声音");
add("我们一起听歌好吗？", "Mình cùng nghe nhạc nhé?", "Mình cùng nghe nhạc nhé?", "共同活动");
add("你喜欢什么类型的电影？", "Em thích thể loại phim gì ạ?", "Em thích thể loại phim gì ạ?", "兴趣话题");
add("我可以每天给你发早安吗？", "Anh nhắn em chào buổi sáng mỗi ngày được không ạ?", "Anh nhắn em chào buổi sáng mỗi ngày được không ạ?", "每日问候");
add("你今天好可爱", "Hôm nay em dễ thương quá ạ", "Hôm nay em dễ thương quá ạ", "夸可爱");
add("我想保护你", "Anh muốn bảo vệ em ạ", "Anh muốn bảo vệ em ạ", "表达保护欲");
add("你累不累？要不要靠我肩膀", "Em mệt không? Dựa vai anh nhé", "Em mệt không?...", "关心+亲密");
add("跟你聊天我都不想停", "Nói chuyện với em anh không muốn dừng ạ", "Nói chuyện với em anh không muốn dừng ạ", "表达不舍");
add("你是我的幸运星", "Em là ngôi sao may mắn của anh ạ", "Em là ngôi sao may mắn của anh ạ", "浪漫比喻");
add("我好想每天都见到你", "Anh muốn gặp em mỗi ngày ạ", "Anh muốn gặp em mỗi ngày ạ", "表达想念");
add("你今天开心我就开心", "Em vui là anh vui rồi ạ", "Em vui là anh vui rồi ạ", "情感绑定");
add("我们一起看星星好吗？", "Mình cùng ngắm sao nhé?", "Mình cùng ngắm sao nhé?", "浪漫活动邀请");
add("你是我的小太阳", "Em là mặt trời nhỏ của anh ạ", "Em là mặt trời nhỏ của anh ạ", "甜蜜比喻");
add("我可以每天给你发晚安吗？", "Anh nhắn em chúc ngủ ngon mỗi tối được không ạ?", "Anh nhắn em chúc ngủ ngon mỗi tối được không ạ?", "晚安问候");
add("你今天好温柔", "Hôm nay em dịu dàng quá ạ", "Hôm nay em dịu dàng quá ạ", "夸气质");
add("我好想一直陪着你", "Anh muốn ở bên em mãi ạ", "Anh muốn ở bên em mãi ạ", "表达长久陪伴");
add("你的手好软", "Tay em mềm quá ạ", "Tay em mềm quá ạ", "触感描述");
add("你是我的宝贝", "Em là cưng của anh ạ", "Em là cưng của anh ạ", "cưng=宝贝");
add("我想每天都抱抱你", "Anh muốn ôm em mỗi ngày ạ", "Anh muốn ôm em mỗi ngày ạ", "表达亲密渴望");
add("你是我的全世界", "Em là cả thế giới của anh ạ", "Em là cả thế giới của anh ạ", "甜蜜告白");
add("我想一直牵你的手", "Anh muốn nắm tay em mãi ạ", "Anh muốn nắm tay em mãi ạ", "牵手表白");
add("跟你在一起的每一秒都很幸福", "Mỗi giây bên em anh đều hạnh phúc ạ", "Mỗi giây bên em anh đều hạnh phúc ạ", "幸福感表达");

// ── table(5).csv — 追求表白 (50) ──
add("我想认真追求你", "Anh muốn theo đuổi em nghiêm túc ạ", "Anh muốn theo đuổi em nghiêm túc ạ", "正式表白追求");
add("你就是我一直在找的那个人", "Em chính là người anh đang tìm kiếm ạ", "Em chính là người anh đang tìm kiếm ạ", "命中注定表达");
add("我会努力让你喜欢上我", "Anh sẽ cố gắng để em thích anh ạ", "Anh sẽ cố gắng để em thích anh ạ", "表决心");
add("我每天都想见到你", "Mỗi ngày anh đều muốn gặp em ạ", "Mỗi ngày anh đều muốn gặp em ạ", "表达思念");
add("我可以每天给你发消息吗？", "Anh nhắn tin cho em mỗi ngày được không ạ?", "Anh nhắn tin cho em mỗi ngày được không ạ?", "日常联系请求");
add("我想带你去很多地方玩", "Anh muốn đưa em đi nhiều nơi ạ", "Anh muốn đưa em đi nhiều nơi ạ", "旅行承诺");
add("你是我遇过最特别的人", "Em là người đặc biệt nhất anh từng gặp ạ", "Em là người đặc biệt nhất anh từng gặp ạ", "特别赞美");
add("我不想错过你", "Anh không muốn bỏ lỡ em ạ", "Anh không muốn bỏ lỡ em ạ", "珍惜表达");
add("让我来照顾你好吗？", "Để anh chăm sóc em nhé ạ", "Để anh chăm sóc em nhé ạ", "照顾承诺");
add("我会证明给你看我是认真的", "Anh sẽ chứng minh cho em thấy anh chân thành ạ", "Anh sẽ chứng minh cho em thấy anh chân thành ạ", "真诚表白");
add("你愿意给我一个机会吗？", "Em cho anh cơ hội nhé ạ", "Em cho anh cơ hội nhé ạ", "请求机会");
add("我对你一见钟情", "Anh thích em từ cái nhìn đầu tiên ạ", "Anh thích em từ cái nhìn đầu tiên ạ", "一见钟情");
add("每次想到你就忍不住笑", "Mỗi lần nghĩ đến em là anh cười ạ", "Mỗi lần nghĩ đến em là anh cười ạ", "思念表达");
add("我想成为你身边的那个人", "Anh muốn là người ở bên em ạ", "Anh muốn là người ở bên em ạ", "陪伴表白");
add("给我点时间，我会让你喜欢我", "Hãy cho anh thời gian để chinh phục em ạ", "Hãy cho anh thời gian để chinh phục em ạ", "chinh phục=征服/追求");
add("你太吸引人了，我忍不住想追你", "Em đẹp quá, anh không kìm được muốn theo đuổi ạ", "Em đẹp quá...", "直白表达吸引力");
add("我会让你每天都开心", "Anh sẽ làm em vui mỗi ngày ạ", "Anh sẽ làm em vui mỗi ngày ạ", "快乐承诺");
add("你给了我很多灵感", "Em là nguồn cảm hứng của anh ạ", "Em là nguồn cảm hứng của anh ạ", "灵感表达");
add("我不完美，但我会为你努力", "Anh không hoàn hảo, nhưng anh sẽ cố gắng vì em ạ", "Anh không hoàn hảo...", "谦虚+决心");
add("让我留在你身边好吗？", "Hãy để anh ở bên em nhé ạ", "Hãy để anh ở bên em nhé ạ", "请求陪伴");
add("我想一直照顾你", "Anh muốn chăm sóc em ạ", "Anh muốn chăm sóc em ạ", "照顾承诺");
add("你愿意让我喜欢你吗？", "Em cho anh cơ hội yêu em được không ạ?", "Em cho anh cơ hội yêu em được không ạ?", "温柔请求");
add("我真的很喜欢你", "Anh thích em nhiều lắm ạ", "Anh thích em nhiều lắm ạ", "直白表白");
add("我不会让你伤心", "Anh sẽ không làm em buồn ạ", "Anh sẽ không làm em buồn ạ", "承诺不伤害");
add("让我证明我的心意给你看", "Hãy để anh chứng minh tình cảm ạ", "Hãy để anh chứng minh tình cảm ạ", "证明真心");
add("你就是我每天开心的原因", "Em là lý do anh cười mỗi ngày ạ", "Em là lý do anh cười mỗi ngày ạ", "快乐源泉");
add("我想成为你最信任的人", "Anh muốn là người em tin tưởng ạ", "Anh muốn là người em tin tưởng ạ", "信任表达");
add("给我机会让我让你幸福", "Hãy cho anh cơ hội làm em hạnh phúc ạ", "Hãy cho anh cơ hội làm em hạnh phúc ạ", "幸福承诺");
add("我会一直在这里等你", "Anh sẽ luôn ở đây chờ em ạ", "Anh sẽ luôn ở đây chờ em ạ", "等候承诺");
add("你就是我想要的一切", "Em là tất cả những gì anh cần ạ", "Em là tất cả những gì anh cần ạ", "极致表白");
add("我想和你一起经历所有", "Anh muốn cùng em trải qua mọi thứ ạ", "Anh muốn cùng em trải qua mọi thứ ạ", "共同经历");
add("让我来爱你好吗？", "Hãy để anh yêu thương em ạ", "Hãy để anh yêu thương em ạ", "请求爱的机会");
add("我不想只做朋友", "Anh không muốn chỉ làm bạn ạ", "Anh không muốn chỉ làm bạn ạ", "跨越友谊");
add("你知道我每天想你多少次吗？", "Em có biết anh nghĩ về em nhiều thế nào không ạ?", "Em có biết anh nghĩ về em nhiều thế nào không ạ?", "思念量化");
add("我会耐心等你", "Anh sẽ kiên nhẫn chờ em ạ", "Anh sẽ kiên nhẫn chờ em ạ", "耐心等待");
add("你就是我的梦想", "Em là giấc mơ của anh ạ", "Em là giấc mơ của anh ạ", "梦想比喻");
add("我想让你每天都笑", "Anh muốn làm em cười mỗi ngày ạ", "Anh muốn làm em cười mỗi ngày ạ", "快乐承诺");
add("让我走进你的世界", "Hãy để anh bước vào thế giới của em ạ", "Hãy để anh bước vào thế giới của em ạ", "浪漫请求");
add("我喜欢你已经很久了", "Anh thích em từ rất lâu rồi ạ", "Anh thích em từ rất lâu rồi ạ", "长期暗恋");
add("给我一个机会好吗？", "Em cho anh cơ hội được không ạ?", "Em cho anh cơ hội được không ạ?", "恳求机会");
add("我想成为你生命中特别的那个人", "Anh muốn là người đặc biệt của em ạ", "Anh muốn là người đặc biệt của em ạ", "特别关系");
add("我不会轻易放弃", "Anh sẽ không bỏ cuộc ạ", "Anh sẽ không bỏ cuộc ạ", "坚持不放弃");
add("我想和你共度一生", "Em là người anh muốn dành cả đời bên cạnh ạ", "Em là người anh muốn dành cả đời bên cạnh ạ", "终生承诺");
add("我想永远照顾你", "Anh muốn chăm sóc em mãi mãi ạ", "Anh muốn chăm sóc em mãi mãi ạ", "永远照顾");
add("让我用我的方式爱你", "Hãy để anh yêu em theo cách của anh ạ", "Hãy để anh yêu em theo cách của anh ạ", "独特爱法");
add("你是我努力的动力", "Em là lý do anh cố gắng mỗi ngày ạ", "Em là lý do anh cố gắng mỗi ngày ạ", "动力源泉");
add("我想和你一起规划未来", "Anh muốn xây dựng tương lai cùng em ạ", "Anh muốn xây dựng tương lai cùng em ạ", "未来规划");
add("让我证明我配得上你", "Hãy để anh chứng minh anh xứng đáng ạ", "Hãy để anh chứng minh anh xứng đáng ạ", "证明配得上");
add("我会等你，无论多久", "Anh sẽ chờ em, dù bao lâu cũng được ạ", "Anh sẽ chờ em, dù bao lâu cũng được ạ", "无限等待");

// ── table(7).csv — 表白告白 (50) ──
add("我爱你", "Anh yêu em ạ", "Anh yêu em ạ", "最经典的三个字");
add("你就是我的全部", "Em là tất cả của anh ạ", "Em là tất cả của anh ạ", "极致表白");
add("没有你我活不下去", "Không có em anh sống không nổi ạ", "Không có em anh sống không nổi ạ", "夸张表达依赖");
add("你是我最爱的人", "Em là người anh yêu nhất ạ", "Em là người anh yêu nhất ạ", "最爱的人");
add("我真的很爱你", "Anh yêu em rất nhiều ạ", "Anh yêu em rất nhiều ạ", "强调真心");
add("你是我的心肝宝贝", "Em là trái tim của anh ạ", "Em là trái tim của anh ạ", "心肝宝贝");
add("我想永远和你在一起", "Anh muốn ở bên em mãi mãi ạ", "Anh muốn ở bên em mãi mãi ạ", "永远在一起");
add("你让我每天都开心", "Em làm anh hạnh phúc mỗi ngày ạ", "Em làm anh hạnh phúc mỗi ngày ạ", "每日幸福");
add("我爱你胜过爱自己", "Anh yêu em hơn cả bản thân anh ạ", "Anh yêu em hơn cả bản thân anh ạ", "超越自我");
add("你就是我的命中注定", "Em là định mệnh của anh ạ", "Em là định mệnh của anh ạ", "命中注定");
add("我从心底爱你", "Anh yêu em từ tận đáy lòng ạ", "Anh yêu em từ tận đáy lòng ạ", "发自内心");
add("没有你，生活没意思", "Không có em, cuộc sống anh vô nghĩa ạ", "Không có em, cuộc sống anh vô nghĩa ạ", "表达重要性");
add("你是我想娶回家的人", "Em là người anh muốn kết hôn ạ", "Em là người anh muốn kết hôn ạ", "求婚暗示");
add("我只希望你幸福", "Anh chỉ muốn em hạnh phúc ạ", "Anh chỉ muốn em hạnh phúc ạ", "无私的爱");
add("你是我的光", "Em là ánh sáng của anh ạ", "Em là ánh sáng của anh ạ", "光明比喻");
add("我爱你，不管你接不接受", "Anh yêu em, dù em có chấp nhận hay không ạ", "Anh yêu em, dù em có chấp nhận hay không ạ", "无条件的爱");
add("你是我最美的梦", "Em là giấc mơ đẹp nhất của anh ạ", "Em là giấc mơ đẹp nhất của anh ạ", "最美的梦");
add("我想和你一起走完下半辈子", "Anh muốn xây dựng tương lai cùng em ạ", "Anh muốn xây dựng tương lai cùng em ạ", "共同未来");
add("你是我活下去的理由", "Em là lý do anh sống ạ", "Em là lý do anh sống ạ", "生存理由");
add("我爱你超过世界上一切", "Anh yêu em hơn tất cả mọi thứ trên đời ạ", "Anh yêu em hơn tất cả mọi thứ trên đời ạ", "超越一切");
add("我想每天醒来都看到你", "Em là người anh muốn thức dậy bên cạnh mỗi sáng ạ", "Em là người anh muốn thức dậy bên cạnh mỗi sáng ạ", "每日醒来的愿望");
add("爱上你是我最正确的决定", "Anh không hối hận khi yêu em ạ", "Anh không hối hận khi yêu em ạ", "不后悔的决定");
add("你是我梦寐以求的人", "Em là tất cả những gì anh mơ ước ạ", "Em là tất cả những gì anh mơ ước ạ", "梦寐以求");
add("我爱你，没有条件", "Anh yêu em vô điều kiện ạ", "Anh yêu em vô điều kiện ạ", "无条件的爱");
add("你是我想共度一生的人", "Em là người phụ nữ anh muốn dành cả đời bên cạnh ạ", "Em là người phụ nữ anh muốn dành cả đời bên cạnh ạ", "一生伴侣");
add("我会爱你到永远", "Anh sẽ yêu em đến cuối cuộc đời ạ", "Anh sẽ yêu em đến cuối cuộc đời ạ", "永远的爱");
add("因为你，我相信真爱", "Em làm anh tin vào tình yêu đích thực ạ", "Em làm anh tin vào tình yêu đích thực ạ", "真爱信仰");
add("我爱你，我想让你知道", "Anh yêu em, và anh muốn em biết điều đó ạ", "Anh yêu em, và anh muốn em biết điều đó ạ", "坦白表白");
add("没有你我不是完整的", "Không có em, anh không còn là chính mình ạ", "Không có em, anh không còn là chính mình ạ", "不完整的自己");
add("你是我心里唯一的人", "Em là người duy nhất trong tim anh ạ", "Em là người duy nhất trong tim anh ạ", "唯一的人");
add("我爱你，不管发生什么", "Anh yêu em, dù có chuyện gì xảy ra ạ", "Anh yêu em, dù có chuyện gì xảy ra ạ", "无论如何");
add("你是我最大的幸福", "Em là hạnh phúc lớn nhất của anh ạ", "Em là hạnh phúc lớn nhất của anh ạ", "最大幸福");
add("我想你永远留在我身边", "Anh muốn em mãi ở bên anh ạ", "Anh muốn em mãi ở bên anh ạ", "永远身边");
add("你让我每天都微笑", "Em là lý do anh mỉm cười mỗi ngày ạ", "Em là lý do anh mỉm cười mỗi ngày ạ", "微笑的理由");
add("我爱你胜过全世界", "Anh yêu em hơn cả thế giới ạ", "Anh yêu em hơn cả thế giới ạ", "超越世界");
add("没有你我无法想象生活", "Anh không thể tưởng tượng cuộc sống không có em ạ", "Anh không thể tưởng tượng cuộc sống không có em ạ", "无法想象没有你");
add("你是我想一起结婚的人", "Em là người phụ nữ anh muốn kết hôn ạ", "Em là người phụ nữ anh muốn kết hôn ạ", "结婚意愿");
add("我用全部的心爱你", "Anh yêu em bằng cả trái tim ạ", "Anh yêu em bằng cả trái tim ạ", "全心全意");
add("你就是我的一切需要", "Em là tất cả những gì anh cần ạ", "Em là tất cả những gì anh cần ạ", "一切所需");
add("我想你永远属于我", "Anh muốn em là của anh mãi mãi ạ", "Anh muốn em là của anh mãi mãi ạ", "永远拥有");
add("因为你，我重新相信爱情", "Em làm anh tin vào tình yêu một lần nữa ạ", "Em làm anh tin vào tình yêu một lần nữa ạ", "重新相信爱");
add("我爱你，会一直爱下去", "Anh yêu em, và sẽ yêu em mãi ạ", "Anh yêu em, và sẽ yêu em mãi ạ", "持续的爱");
add("你是我活着的意义", "Em là nguồn sống của anh ạ", "Em là nguồn sống của anh ạ", "生命意义");
add("我不想失去你", "Anh không muốn mất em ạ", "Anh không muốn mất em ạ", "害怕失去");
add("我的爱永远不变", "Anh yêu em, không gì thay đổi được ạ", "Anh yêu em, không gì thay đổi được ạ", "不变的爱");
add("你就是我的幸福", "Em là hạnh phúc của anh ạ", "Em là hạnh phúc của anh ạ", "幸福本身");
add("我爱你，爱到无法形容", "Anh yêu em đến mức không thể diễn tả ạ", "Anh yêu em đến mức không thể diễn tả ạ", "无法形容的爱");
add("你是我的永远", "Em là mãi mãi của anh ạ", "Em là mãi mãi của anh ạ", "永恒的你");

// ── table(8).csv — 自然升温口语 (50) ──
add("跟你在一起的感觉真的挺舒服的", "Ở bên em cảm giác thật thoải mái ạ", "Ở bên em cảm giác thật thoải mái ạ", "自然表达舒适");
add("我觉得你这个人挺特别的", "Anh thấy em đặc biệt lắm ạ", "Anh thấy em đặc biệt lắm ạ", "含蓄赞美");
add("如果你有空的话，我们可以再一起出来玩", "Nếu em rảnh thì mình gặp lại đi chơi nhé ạ", "Nếu em rảnh thì mình gặp lại đi chơi nhé ạ", "委婉约下次");
add("有时候莫名其妙就会想到你", "Có lúc anh tự nhiên nghĩ đến em ạ", "Có lúc anh tự nhiên nghĩ đến em ạ", "自然思念");
add("跟你聊天的时候时间过得特别快", "Nói chuyện với em thời gian trôi nhanh thật ạ", "Nói chuyện với em thời gian trôi nhanh thật ạ", "享受聊天");
add("感觉我们俩还挺有缘分的", "Hình như mình có duyên thật đấy ạ", "Hình như mình có duyên thật đấy ạ", "缘分表达");
add("希望以后还能多见几次你", "Hy vọng sau này mình còn gặp nhau nhiều hơn ạ", "Hy vọng sau này mình còn gặp nhau nhiều hơn ạ", "期望再见");
add("跟你待着就觉得心情很好", "Ở bên em anh thấy tâm trạng tốt hẳn lên ạ", "Ở bên em anh thấy tâm trạng tốt hẳn lên ạ", "好心情");
add("我挺喜欢这种慢慢靠近的感觉", "Anh thích cảm giác từ từ gần nhau thế này ạ", "Anh thích cảm giác từ từ gần nhau thế này ạ", "享受慢慢靠近");
add("跟你聊完以后总会想起你说的话", "Nói chuyện xong với em là anh hay nhớ lại lời em nói ạ", "Nói chuyện xong với em là anh hay nhớ lại lời em nói ạ", "回味对话");
add("感觉你懂我很多时候的想法", "Em hiểu ý anh nói đúng không ạ", "Em hiểu ý anh nói đúng không ạ", "默契表达");
add("希望以后还能有这样的下午", "Hy vọng sau này còn nhiều buổi chiều như thế này ạ", "Hy vọng sau này còn nhiều buổi chiều như thế này ạ", "珍惜时光");
add("跟你在一起的时候挺放松的", "Ở bên em anh thấy thoải mái lắm ạ", "Ở bên em anh thấy thoải mái lắm ạ", "放松表达");
add("如果你也觉得开心，我们可以多联系", "Nếu em cũng thấy vui thì mình liên lạc nhiều hơn nhé ạ", "Nếu em cũng thấy vui thì mình liên lạc nhiều hơn nhé ạ", "增加联系");
add("我挺好奇你平时都喜欢做什么", "Anh tò mò về cuộc sống hàng ngày của em lắm ạ", "Anh tò mò về cuộc sống hàng ngày của em lắm ạ", "好奇日常");
add("跟你待着就觉得时间不够用", "Ở bên em anh thấy thời gian không đủ ạ", "Ở bên em anh thấy thời gian không đủ ạ", "时间不够");
add("感觉我们之间好像有点什么", "Anh thấy giữa mình có gì đó đặc biệt ạ", "Anh thấy giữa mình có gì đó đặc biệt ạ", "暗示感情");
add("有时候会想知道你现在在干嘛", "Có lúc anh tự hỏi em đang làm gì ạ", "Có lúc anh tự hỏi em đang làm gì ạ", "思念日常");
add("跟你相处的时候心情总是很好", "Ở bên em anh thấy tâm trạng tốt hẳn ạ", "Ở bên em anh thấy tâm trạng tốt hẳn ạ", "好心情");
add("我挺喜欢这种自然的感觉", "Anh thích cảm giác tự nhiên thế này ạ", "Anh thích cảm giác tự nhiên thế này ạ", "自然舒适");
add("你有没有觉得我们俩挺合拍的", "Em có thấy mình hợp nhau không ạ?", "Em có thấy mình hợp nhau không ạ?", "询问默契");
add("希望下次还能这样坐着聊天", "Hy vọng lần sau mình còn ngồi nói chuyện thế này ạ", "Hy vọng lần sau mình còn ngồi nói chuyện thế này ạ", "期望下次");
add("跟你在一起就觉得安心", "Ở bên em anh thấy yên tâm lắm ạ", "Ở bên em anh thấy yên tâm lắm ạ", "安心感");
add("感觉我们之间有种说不出的默契", "Anh thấy giữa mình có sự ăn ý gì đó ạ", "Anh thấy giữa mình có sự ăn ý gì đó ạ", "默契表达");
add("你有没有偶尔想起我们见面的时候", "Em có hay nhớ những lúc mình gặp nhau không ạ?", "Em có hay nhớ những lúc mình gặp nhau không ạ?", "回忆见面");
add("我挺想再早一点见到你的", "Anh khá muốn gặp em sớm hơn nữa ạ", "Anh khá muốn gặp em sớm hơn nữa ạ", "急切见面");
add("跟你聊天是今天最开心的事", "Nói chuyện với em là chuyện vui nhất hôm nay ạ", "Nói chuyện với em là chuyện vui nhất hôm nay ạ", "最开心的事");
add("感觉我们俩可能真的挺合适的", "Có lẽ mình hợp nhau thật đấy ạ", "Có lẽ mình hợp nhau thật đấy ạ", "试探性表白");
add("跟你待着就觉得世界安静了", "Ở bên em anh thấy thế giới yên bình hẳn ạ", "Ở bên em anh thấy thế giới yên bình hẳn ạ", "平静表达");
add("如果你也觉得这样挺好的，我们可以继续", "Nếu em cũng thấy ổn thì mình cứ tiếp tục nhé ạ", "Nếu em cũng thấy ổn thì mình cứ tiếp tục nhé ạ", "征求继续");
add("你总让我想到很多有趣的事", "Em làm anh nghĩ về nhiều điều thú vị ạ", "Em làm anh nghĩ về nhiều điều thú vị ạ", "有趣联想");
add("如果你也有类似的感觉就太好了", "Nếu em cũng cảm thấy giống anh thì tốt quá ạ", "Nếu em cũng cảm thấy giống anh thì tốt quá ạ", "试探性询问");
add("我挺想多了解你一些", "Anh muốn hiểu em nhiều hơn ạ", "Anh muốn hiểu em nhiều hơn ạ", "深入了解");
add("跟你相处让我觉得生活更有意思", "Em làm anh thấy cuộc sống thú vị hơn ạ", "Em làm anh thấy cuộc sống thú vị hơn ạ", "生活更有趣");
add("我有点想让你知道我在想什么", "Anh muốn em biết anh nghĩ gì về em ạ", "Anh muốn em biết anh nghĩ gì về em ạ", "坦白心意");
add("我们可以试着看看感觉怎么样", "Mình có thể thử xem cảm giác thế nào ạ", "Mình có thể thử xem cảm giác thế nào ạ", "试探关系");
add("我觉得我们之间有种特别的默契", "Anh thấy mình và em có chemistry ạ", "Anh thấy mình và em có chemistry ạ", "chemistry=化学反应/默契");
add("如果你愿意，我可以离你近一点", "Em có muốn anh ở gần em hơn chút nữa không ạ?", "Em có muốn anh ở gần em hơn chút nữa không ạ?", "靠近请求");
add("我特别喜欢只有我们两个的时候", "Anh thích những lúc chỉ có hai ta ạ", "Anh thích những lúc chỉ có hai ta ạ", "独处时光");
add("你有没有觉得跟我在一起有点不一样", "Em có cảm thấy gì đặc biệt khi ở bên anh không ạ?", "Em có cảm thấy gì đặc biệt khi ở bên anh không ạ?", "试探感觉");
add("你总能让我不自觉地笑", "Anh thích cách em làm anh cười ạ", "Anh thích cách em làm anh cười ạ", "自然微笑");
add("如果你不介意，我想多陪陪你", "Nếu em cho phép thì anh sẽ cố gắng hơn ạ", "Nếu em cho phép thì anh sẽ cố gắng hơn ạ", "多陪伴");
add("跟你在一起让我觉得一切都变好了", "Em làm anh thấy cuộc sống đẹp hơn ạ", "Em làm anh thấy cuộc sống đẹp hơn ạ", "美好生活");
add("我们可以试着走近一点吗", "Mình có thể thử tiến thêm một bước không ạ?", "Mình có thể thử tiến thêm một bước không ạ?", "进一步试探");
add("如果你愿意，我可以多陪你一些", "Em có muốn anh ở bên em nhiều hơn không ạ?", "Em có muốn anh ở bên em nhiều hơn không ạ?", "更多陪伴");
add("我特别享受只有我们俩的时光", "Anh thích những lúc chỉ có hai ta ạ", "Anh thích những lúc chỉ có hai ta ạ", "独处时光");
add("如果你也有同样的感觉，我们就继续吧", "Nếu em cũng thấy vậy thì mình cứ tiếp tục nhé ạ", "Nếu em cũng thấy vậy thì mình cứ tiếp tục nhé ạ", "确认继续");

// ── table(9).csv — 亲密升级 (50) ──
add("今晚想和你待得久一点", "Tối nay anh muốn ở bên em lâu hơn ạ", "Tối nay anh muốn ở bên em lâu hơn ạ", "延长共处时间");
add("想和你更亲近一些", "Anh muốn gần em hơn nữa ạ", "Anh muốn gần em hơn nữa ạ", "亲近表达");
add("如果你也想的话，我们可以试试", "Nếu em cũng muốn thì mình thử nhé ạ", "Nếu em cũng muốn thì mình thử nhé ạ", "征求同意");
add("我好想抱你久一点", "Anh muốn ôm em lâu hơn ạ", "Anh muốn ôm em lâu hơn ạ", "延长拥抱");
add("跟你在一起的时候身体好热", "Ở bên em anh thấy nóng hết cả người ạ", "Ở bên em anh thấy nóng hết cả người ạ", "表达心跳加速");
add("想和你一起躺下休息一会儿", "Anh muốn nằm bên em nghỉ ngơi chút ạ", "Anh muốn nằm bên em nghỉ ngơi chút ạ", "休息邀请");
add("如果你愿意，我可以轻轻碰你", "Nếu em thoải mái thì anh chạm nhẹ được không ạ?", "Nếu em thoải mái thì anh chạm nhẹ được không ạ?", "征求触碰同意");
add("今晚感觉特别想靠近你", "Tối nay anh cảm thấy rất muốn gần em ạ", "Tối nay anh cảm thấy rất muốn gần em ạ", "靠近冲动");
add("你的皮肤好软，我想摸一下", "Da em mềm quá, anh muốn chạm thử ạ", "Da em mềm quá, anh muốn chạm thử ạ", "触感赞美");
add("我们可以关灯躺在一起吗？", "Mình tắt đèn nằm bên nhau được không ạ?", "Mình tắt đèn nằm bên nhau được không ạ?", "浪漫邀请");
add("想吻你久一点", "Anh muốn hôn em lâu hơn ạ", "Anh muốn hôn em lâu hơn ạ", "延长亲吻");
add("跟你亲密的时候我好开心", "Khi gần gũi em anh thấy vui lắm ạ", "Khi gần gũi em anh thấy vui lắm ạ", "亲密快乐");
add("想和你一起感受更多", "Anh muốn cùng em cảm nhận nhiều hơn ạ", "Anh muốn cùng em cảm nhận nhiều hơn ạ", "更多感受");
add("今晚想和你更进一步", "Tối nay anh muốn gần em hơn nữa ạ", "Tối nay anh muốn gần em hơn nữa ạ", "进一步表达");
add("如果你不介意，我可以轻轻碰你", "Nếu em không ngại thì anh chạm nhẹ được không ạ?", "Nếu em không ngại thì anh chạm nhẹ được không ạ?", "委婉征求");
add("跟你肌肤相亲的感觉真好", "Cảm giác da chạm da với em thật tuyệt ạ", "Cảm giác da chạm da với em thật tuyệt ạ", "亲密感受");
add("如果你觉得不舒服就告诉我", "Nếu em không thoải mái thì nói anh ngay nhé ạ", "Nếu em không thoải mái thì nói anh ngay nhé ạ", "尊重表达");
add("想和你融为一体", "Anh muốn hòa quyện vào em ạ", "Anh muốn hòa quyện vào em ạ", "浪漫表达");
add("今晚想让你感觉被爱", "Tối nay anh muốn em cảm nhận được tình yêu ạ", "Tối nay anh muốn em cảm nhận được tình yêu ạ", "感受被爱");
add("想和你一起慢慢享受", "Anh muốn cùng em từ từ tận hưởng ạ", "Anh muốn cùng em từ từ tận hưởng ạ", "慢慢享受");
add("你喜欢我轻一点还是用力一点？", "Em muốn anh nhẹ nhàng hay mạnh mẽ hơn ạ?", "Em muốn anh nhẹ nhàng hay mạnh mẽ hơn ạ?", "了解偏好");
add("想让你今晚忘不掉", "Anh muốn tối nay em không quên được ạ", "Anh muốn tối nay em không quên được ạ", "难忘表达");
add("想和你一起达到那种巅峰", "Anh muốn cùng em đạt đến đỉnh cao ạ", "Anh muốn cùng em đạt đến đỉnh cao ạ", "共同巅峰");
add("想让你今晚完全属于我", "Anh muốn tối nay em thuộc về anh ạ", "Anh muốn tối nay em thuộc về anh ạ", "占有表达");
add("想和你一起感受那种亲密", "Anh muốn cùng em cảm nhận sự thân mật ấy ạ", "Anh muốn cùng em cảm nhận sự thân mật ấy ạ", "亲密感受");
add("你喜欢我怎么做最舒服？", "Em thích anh làm thế nào thì em thoải mái nhất ạ?", "Em thích anh làm thế nào thì em thoải mái nhất ạ?", "了解舒适度");
add("想让你今晚感觉被完全宠爱", "Anh muốn tối nay em cảm thấy được yêu chiều ạ", "Anh muốn tối nay em cảm thấy được yêu chiều ạ", "宠爱表达");
add("想和你一起感受那种节奏", "Anh muốn cùng em cảm nhận nhịp điệu ấy ạ", "Anh muốn cùng em cảm nhận nhịp điệu ấy ạ", "共同节奏");
add("你喜欢慢一点还是快一点？", "Em muốn chậm hay nhanh hơn ạ?", "Em muốn chậm hay nhanh hơn ạ?", "节奏偏好");
add("想让你今晚完全放松", "Anh muốn tối nay em hoàn toàn thư giãn ạ", "Anh muốn tối nay em hoàn toàn thư giãn ạ", "放松表达");
add("想和你一起感受那种融合", "Anh muốn cùng em cảm nhận sự hòa quyện ạ", "Anh muốn cùng em cảm nhận sự hòa quyện ạ", "融合表达");
add("你喜欢我温柔一点还是热情一点？", "Em muốn anh nhẹ nhàng hay mạnh mẽ hơn ạ?", "Em muốn anh nhẹ nhàng hay mạnh mẽ hơn ạ?", "风格偏好");

async function main() {
  console.log(`Seeding ${phrases.length} pickup phrases...`);

  // Delete existing pickup phrases
  const del = await prisma.scenePhrase.deleteMany({ where: { scene: "pickup" } });
  console.log(`Deleted ${del.count} existing pickup phrases`);

  // Create new phrases
  const result = await prisma.scenePhrase.createMany({ data: phrases });
  console.log(`Created ${result.count} pickup phrases`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
